image: aneoshun/airl_build_env:latest

stages:
  - build
  - deploy
  
singularity-image:
  stage: build
  script:
     - /bin/bash ./.gitlabci/build_base.sh airl_env_base --nofakeroot 
     - /bin/bash ./.gitlabci/test_images.sh airl_env_base.sif --nofakeroot 
     - if [ $CI_COMMIT_REF_NAME = "master" ]; then /bin/bash ./.gitlabci/push_image.sh airl_env_base --uri library://airl_lab/default/airl_env --tag base_ci --cli registry ; else echo "NOT on master branch, not pushing"; fi; 
  artifacts:
    paths:
       - airl_env_base.def

launch_experiment:
  stage: deploy
  script:
    - /bin/bash ./.gitlabci/launch_exp.sh
  when: manual
  only:
    variables:
      - $CI_COMMIT_REF_PROTECTED =="true"

    