image: aneoshun/airl_build_env:latest

before_script:
  - /bin/bash -c "echo before script"

build:
  script:
     - ls
     - /bin/bash ./build_base.sh --nofakeroot
  artifacts:
     paths:
       - airl_env_base.sif
       - airl_env_base.def
       