image: aneoshun/airl_build_env:latest

stages:
  - build

singularity-image:
  stage: build
  script:
     - echo $CI_COMMIT_REF_NAME
     - exit 1 #/bin/bash ./build_base.sh --nofakeroot
     - exit 1 #/bin/bash ./push_image.sh --uri library://airl_lab/default/airl_env --tag base_ci --cli registry
       