image: aneoshun/airl_build_env:latest

stages:
  - build
  - deploy
  
airl_env_base:
  stage: build
  script:
     - /bin/bash ./.gitlabci/ci_script.sh --basename airl_env_base --tag base_ci
  artifacts:
    paths:
       - airl_env_base.def

airl_env_tensorflow:
  stage: build
  script:
     - /bin/bash ./.gitlabci/ci_script.sh --basename airl_env_tensorflow --tag tensorflow_ci
  artifacts:
    paths:
       - airl_env_tensorflow.def

airl_env_pytorch:
  stage: build
  script:
     - /bin/bash ./.gitlabci/ci_script.sh --basename airl_env_pytorch --tag pytorch_ci
  artifacts:
    paths:
       - airl_env_pytorch.def

airl_env_bare:
  stage: build
  script:
     - /bin/bash ./.gitlabci/ci_script.sh --basename airl_env_bare --tag bare_ci
  artifacts:
    paths:
       - airl_env_bare.def

launch_experiment:
  stage: deploy
  script:
    - /bin/bash ./.gitlabci/launch_exp.sh
  when: manual
  only:
    variables:
      - $CI_COMMIT_REF_PROTECTED =="true"

    