image: aneoshun/airl_build_env:latest

stages:
  - build

singularity-image:
  stage: build
  script:
     - /bin/bash ./build_base.sh --nofakeroot
     - source /sregistry_file
     - echo $SREGISTRY_TOKEN > ~/.singularity/sylabs-token
     - /bin/bash ./push_image.sh --uri library://airl_lab/default/airl_env --tag CI --cli registry
       