# This is a basic workflow to help you get started with Actions

name: Build images
# Controls when the workflow will run
on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  airl_env_bare:
    runs-on: ubuntu-latest
    container: 
      image: aneoshun/airl_build_env:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: cd $GITHUB_WORKSPACE && ls && /bin/bash ./.ci/ci_script.sh --basename airl_env_bare --tag "${GITHUB_SHA}" --token ${{ secrets.GITHUB_TOKEN }}
        
  airl_env_qdax:
    runs-on: ubuntu-latest
    container: 
      image: aneoshun/airl_build_env:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: cd $GITHUB_WORKSPACE && ls && /bin/bash ./.ci/ci_script.sh --basename airl_env_qdax --tag "${GITHUB_SHA}" --token ${{ secrets.GITHUB_TOKEN }}

 
